#!/usr/bin/env python
# 
# simply show image

import cv
import cv2
import numpy as np

import sys

# funcs

def showimage(filename):
    img = cv2.imread(filename, 1)
    cv2.namedWindow(filename, 0)
    cv2.imshow(filename, img)

# load file

if(len(sys.argv) < 2):
    print 'usage: python %s [input.jpg]' % sys.argv[0]
    quit()

for infile in sys.argv[1:]:
    try:
        print "show %s" % infile
        showimage(infile)
    except:
        print 'fail to load %s' % infile
        quit()

cv2.waitKey(0)

